### ISSUE TITLE
I can't remove timezones in gnome 3.34.2

### ISSUE THREAD

**Issue by edurenye** [Masquerade-Circus/gnome-timezones-extension#1]
I'm using ubuntu 19.10 and gnome 3.34.2 and I can add new timezones, but the if i try to remove them, it adds a random new one, and when I have more than four timezones, I'm able to remove the ones on top, it's kind of weird bug.
So, from the screenshot, there are 5 options in my list of active clocks, the one on top, when I put the cursor on top of it, the background is grey as you can see, but if I move the cursor to the option below, the background of that option is not grayed, so if I click the first one, it gets removed, but if I click the second one to remove it, instead of removing it, it adds another random clock to the active clocks. My guess is the acts like the active clock are transparent and clicks some list hidden behind or something strange.
![Screenshot from 2020-04-23 12-13-34](https://user-images.githubusercontent.com/6824576/80088427-cb266d00-855c-11ea-95ba-e1010c04d451.png)

**Comment by edurenye** [comment]
Maybe would be nicer to just have the active clocks in the dropdown, and a button that opens a configuration window were you can add more active clocks and change the settings. Or something like that.

**Comment by richardelloyd** [comment]
I have to uninstall this, because it's happening to me too. Will check back in case it's updated
![image](https://user-images.githubusercontent.com/56018/87170672-a611e280-c29f-11ea-99ef-9c723bbe4522.png)

**Comment by alenbasic** [comment]
I use this extension as well and have encountered the problem mentioned here. I've forked the repo and begun investigating it. I'll send through a pull request once I've gotten around to figuring out what's going on. I'll post another comment here once that's done so others can follow what's going on. That said, I may end up maintaining a separate version anyway as there's some changes I'm looking to make that are somewhat drastic to suit my own needs.

**Comment by ddnexus** [comment]
Work around: disable and enable the extension. After that it should work as expected.

**Comment by poppafuze** [comment]
Actually, disabling and enabling does not make the problem go away and it still does not work as expected.  It is not a workaround.

**Comment by robmsmt** [comment]
+1 for this bug. It's strange, I think it is reproducible if you add/remove a timezone a few times. I have moved to gnome 40 in ubuntu 21.10 and can no longer use this extension unfortunately.

**Comment by ddnexus** [comment]
@poppafuze the efficacy of the workaround has obviously something to do with the rest if the environment

**Comment by Masquerade-Circus** [comment]
This problem is related to the scroll box of the timezones panel. The workaround is to scroll to top and then click on the clock that you want to remove.
I have updated the extension to work with gnome ^40 and the issue has been resolved.
I also added a `Clear clocks` option that removes all the active clocks on the config section.

https://extensions.gnome.org/extension/2657/timezones-extension/

**Comment by mfuhrmann** [comment]
Shouldn't this be also fixed in for example 3.36.8? 
I mean, this Gnome version is rolled out in the current Ubuntu 20 LTS release which is more or less a default OS in a lot companies. Not sure when Ubuntu will provide newer Gnome versions.
