### ISSUE TITLE
Clicking creates yet another item

### ISSUE THREAD

**Issue by poppafuze** [Masquerade-Circus/gnome-timezones-extension#8]
Any click creates another unwanted timezone until my task bar is full.  The docs do not describe where the config is to manually edit.  Thanks for creating the extension.

**Comment by poppafuze** [comment]
It actually creates so many items that it overruns my Applications and Places and they no longer work.

**Comment by poppafuze** [comment]
![Screenshot from 2021-07-21 05-04-09](https://user-images.githubusercontent.com/174006/126462700-4fa32cc6-cfaf-491f-beae-f851225890d7.png)

**Comment by robmsmt** [comment]
this is the same as issue #1
